### PR TITLE
New API endpoint to allow TN to fetch FD User ids for TN members

### PR DESCRIPTION
**Pull request by scyclops**
I thought I might try a different way of making feature requests :)

I based this off the http/api/profile.php file but I haven't tested this code.  And of course feel free to rename things to fit your naming preferences.

### CODE REVIEW

**Comment by scyclops** [comment]
It appears the build failed because of a geoipupdate issue unrelated to this pull request.

"The command "sudo geoipupdate -v -f /tmp/GeoIP.conf" failed and exited with 1 during ."

**Comment by edwh** [comment]
Thanks, I'll have a look.

**Comment by edwh** [comment]
Was that the docker image? It's a while since I used that, and I think the geoip folk made some changes to do with licensing. I think I sorted that for Travis tests, but perhaps not for docker.

**Comment by scyclops** [comment]
I'm not sure what Travis CI is using to do the build but you can find the build details at:

https://travis-ci.com/github/Freegle/iznik-server/builds/153221948

**Comment by edwh** [comment]
Oh, you're doing a travis run on a branch.  Nice, I didn't know it let 
you.

Probably the lack of env variables.  I'll restart that build and see if 
it runs ok, out of interest.

Will try to review it soon.  I'm a bit flat out on other stuff.

------ Original Message ------

**Comment by edwh** [comment]
Actually, might as well review it now.

I don't have dashes in API call names.  It would be more in keeping with the rest of the API to have this handed in user.php, similarly to how we handle emails as around l24.  

There is a slight security hole here.
* You can use the API call as it currently stands to establish the user id for an email address, and therefore establish whether or not someone has an account on the site, or check whether a user id is the same as the email you think they might have.  
* I don't think there's a valid reason to allow that, so I'd probably want to place some restrictions based on the role of the currently logged in user/partner.  That would also then ensure that you could query for TN users only rather than other domains.

It needs some UTs, too.

But it's an innovative way to nudge me to do the work :-).

**Comment by scyclops** [comment]
Good points.  

In a perfect world, TN would make an API request to subscribe people to groups on FD and then that response would just return the TN users FD User id.  But I didn't want to depend on the email API any more than we already are by trying to hack this into an email header.  So the hash to User id solution seemed the simplest way for me to implement this.

Do you want me to take a stab at the improvements you suggested?  When I was reading the code earlier I didn't find very much code around partners and their access/roles which is why I only did the simple $_SESSION partner check.

**Comment by edwh** [comment]
You're right, there is little code round partners - all it really does 
is allow you to have member access on a group rather than non-member, to 
avoid you having to log in to get some info.

There is a partners_keys table which really ought to have a domain name 
column (update schema.sql).  Once we had that, then we could then give 
you mod rights on any user with an email address which was in that 
domain.  That would probably be the way to go, with that logic being 
inside User.php, similar to getRoleForGroup.

If you want to have a stab at it while you're self-isolating then be my 
guest.

Once I've finished rewriting MT, then I may turn my attention to 
rewriting the server - that PHP code is a bit gnarly now, and the API is 
weird.  But I'm not sure, because there's a lot of subtle stuff in there 
that would easily be broken, and it might just be a self-indulgent 
code-tidy.

------ Original Message ------

**Comment by scyclops** [comment]
I'm closing this because I've implemented a different solution that doesn't require any FD changes (the user ID can be parsed from the chat notification email addresses that TN receives notify-[chatid]-[recipient-user-id]).

**Pull request closed without merging**
