### PR TITLE
Fix CORS for iOS WKWebView in app

### PR DESCRIPTION
**Pull request by chriscant**
This gets the app working using new WKWebView CORS requirements

### CODE REVIEW

**Comment by edwh** [comment]
You've reinstated the *.  Isn't that going to cause duplicates, like you saw before?

I'm sure I've seen problems in the past when you send allow headers back that were not requested, so I'm worried about that being safe.  What's the specific change you're trying to make here?

**Comment by chriscant** [comment]
Adding the * back in is what seems to be needed for this to work in new iOS app.

The problem requested headers only contained authorization.
Adding X-HTTP-Method-Override was crucial.
But adding that in only if requested headers was blank didn't work.

**Comment by edwh** [comment]
So does it put duplicate stars in now?  Because we definitely removed it for that reason - see commit on 02/01.

The headers fix doesn't seem safe enough.  How about adding in X-HTTP-Method-Override as well as what was requested?

**Comment by chriscant** [comment]
I'm testing at fdapidev.
In the iOS network tab I am not seeing two stars.
I'll try adding X-HTTP-Method-Override to see if that suffices.

**Comment by edwh** [comment]
I can see that I commented out the adding of * in the nginx config, probably in late Feb.  So that is reassuring.  The live site uses /api rather than a separate hostname, so it is looking like I broke CORS while doing whatever it was we don't remember. So I'm OK with putting the * back.

Ta for looking into the headers.

**Comment by chriscant** [comment]
Argh - it looks a horrible PHP parsing error on the Access-Control-Allow-Headers line.
Just need some round brackets and we're OK.
I'll double-check after lunch.

**Comment by chriscant** [comment]
The latest commit I think appears in this pull request.
It still adds the star but instead tweaks the original Access-Control-Allow-Headers line.

**Comment by edwh** [comment]
That's live now.

**Pull request merged**
